In [1]:
from tensorflow.keras.preprocessing.image import load_img
from tensorflow.keras.preprocessing.image import img_to_array
from tensorflow.keras.preprocessing.image import array_to_img
import os

C:\Users\Girija Joshi\anaconda3\envs\PythonData\lib\site-packages\tensorflow\python\framework\dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\Girija Joshi\anaconda3\envs\PythonData\lib\site-packages\tensorflow\python\framework\dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\Girija Joshi\anaconda3\envs\PythonData\lib\site-packages\tensorflow\python\framework\dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\Girija Joshi\anaconda3\envs\

In [2]:
file_path = os.path.join('./Resources/IDC_regular_ps50_idx5/8863/1','8863_idx5_x1001_y801_class1.png')
print(file_path)
# load the image
img = load_img(file_path, target_size = (50,50))
# report details about the image
print(type(img))
print(img.format)
print(img.mode)
print(img.size)
# show the image
img.show()

./Resources/IDC_regular_ps50_idx5/8863/1\8863_idx5_x1001_y801_class1.png
<class 'PIL.PngImagePlugin.PngImageFile'>
PNG
RGB
(50, 50)


### img_to_array will take PIL Image instance and turn it into a numpy array, with dtype float32. If you start from a PNG image, the values inside the image will lie between 0 and 255. This is usually represented by an 8-bit unsigned integer; img_to_array however will cast to float.

In [3]:
# Keras provides the img_to_array() function for converting a loaded image in PIL format into a NumPy array 
# for use with deep learning models. The image is convertated into t [height, width, channels]

# # Arguments
#         img: PIL Image instance.
#         data_format: Image data format,
#             either "channels_first" or "channels_last".
#         dtype: Dtype to use for the returned array.
# Returns: A 3D Numpy array.

# The component values are often stored as integer numbers in the range 0 to 255, 
# the range that a single 8-bit byte can offer,


img_array = img_to_array(img)
print(img_array.dtype)
print(img_array.shape)

print(img_array)

# converting into 0 - 1, This is called as Normalization will help you to remove distortions 
# caused by lights and shadows in an image.
img_array /= 255
print('\n-----------------------------------------------------')
print(img_array)

# convert back to image
print('\n-----------------------------------------------------')
img_pil = array_to_img(img_array)
print(type(img_pil))

float32
(50, 50, 3)
[[[209. 101. 135.]
  [206.  99. 142.]
  [194. 103. 142.]
  ...
  [207.  91. 127.]
  [211. 104. 141.]
  [205. 106. 144.]]

 [[213. 114. 144.]
  [210. 136. 170.]
  [209. 101. 140.]
  ...
  [219. 123. 157.]
  [216. 126. 163.]
  [206.  97. 136.]]

 [[209. 101. 136.]
  [212.  91. 122.]
  [206.  97. 127.]
  ...
  [221. 124. 160.]
  [218. 112. 147.]
  [206.  84. 121.]]

 ...

 [[147.  94. 137.]
  [149.  88. 135.]
  [114.  70. 121.]
  ...
  [186.  97. 140.]
  [187. 123. 157.]
  [172. 121. 158.]]

 [[120.  67. 120.]
  [138.  85. 134.]
  [103.  60. 107.]
  ...
  [202. 150. 173.]
  [177. 135. 170.]
  [169.  72. 111.]]

 [[150. 118. 146.]
  [188. 154. 190.]
  [224. 194. 213.]
  ...
  [166.  70. 114.]
  [193. 102. 137.]
  [215. 154. 181.]]]
[[[0.81960785 0.39607844 0.5294118 ]
  [0.80784315 0.3882353  0.5568628 ]
  [0.7607843  0.40392157 0.5568628 ]
  ...
  [0.8117647  0.35686275 0.49803922]
  [0.827451   0.40784314 0.5529412 ]
  [0.8039216  0.41568628 0.5647059 ]]

 [[0.8352941